# Generated by Django 4.2.2 on 2023-06-21 19:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('depart_date', models.DateField()),
                ('arriving_date', models.DateField()),
                ('economy_seats', models.IntegerField()),
                ('first_class_seats', models.IntegerField()),
                ('business_class_seats', models.IntegerField()),
                ('economy_seat_price', models.IntegerField()),
                ('first_class_seat_price', models.IntegerField()),
                ('business_class_seat_price', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('depart_date', models.DateField()),
                ('arriving_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('ticket_type', models.CharField(choices=[('econom', 'Economy'), ('first', 'First Class'), ('business', 'Business Class')], max_length=100)),
                ('canceled_by', models.CharField(choices=[('client', 'Client'), ('admin', 'Admin')], max_length=100)),
                ('booking_id', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ticket')),
            ],
        ),
    ]
