# Generated by Django 4.2.2 on 2023-06-21 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='arriving_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='depart_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='from_location',
        ),
        migrations.AddField(
            model_name='ticket',
            name='allowance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.allowance'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='discount_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=datetime.date.today)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('allowance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.allowance')),
            ],
        ),
    ]
