# Generated by Django 4.2.2 on 2023-06-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_ticket_arriving_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='arriving_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='depart_date',
            field=models.DateTimeField(),
        ),
    ]
