# Generated by Django 4.2.2 on 2023-06-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_allowance_arriving_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='canceled_by',
            field=models.CharField(choices=[('client', 'Client'), ('none', 'None')], max_length=100),
        ),
    ]
