# Generated by Django 4.2.2 on 2023-06-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='deleted',
            new_name='deleted_at',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
